
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sspf.c
OBJSC    = sspf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscts
LOCDIR   = src/ts/impls/explicit/ssp/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
