
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = sundialsf.c
OBJSC    = sundialsf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscts
LOCDIR   = src/ts/impls/implicit/sundials/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
