
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  = 
CFLAGS   =
FFLAGS   =
SOURCEC  = matlabf.c
OBJSC    = matlabf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/matlabengine/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
