
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dclearf.c dflushf.c dlinewf.c dtrif.c dsclearf.c dmousef.c dgpausef.c dellipsef.c dbufff.c dgcoorf.c drawf.c dlinegwf.c dlinef.c drectf.c dsetpausef.c dpausef.c dtextgsf.c dpointf.c dsflushf.c dviewpf.c dtextsf.c dcoorf.c dpointsf.c
OBJSC    = dclearf.o dflushf.o dlinewf.o dtrif.o dsclearf.o dmousef.o dgpausef.o dellipsef.o dbufff.o dgcoorf.o drawf.o dlinegwf.o dlinef.o drectf.o dsetpausef.o dpausef.o dtextgsf.o dpointf.o dsflushf.o dviewpf.o dtextsf.o dcoorf.o dpointsf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/draw/interface/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
