
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mpibaijf.c
OBJSC    = mpibaijf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	 = libpetscmat
LOCDIR	 = src/mat/impls/baij/mpi/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
