
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = da2f.c dadistf.c daf.c fddaf.c daindexf.c daltolf.c dacornf.c dagtonaf.c dagetarrayf.c daghostf.c gr1f.c dagtolf.c dacreatef.c dainterpf.c
OBJSC    = da2f.o dadistf.o daf.o fddaf.o daindexf.o daltolf.o dacornf.o dagtonaf.o dagetarrayf.o daghostf.o gr1f.o dagtolf.o dacreatef.o dainterpf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/da/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
