
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
OBJSC    = 
SOURCEF  =
SOURCEH  = petscksp.h90 petscpc.h90 petscdmcomposite.h90 petscdraw.h90 petscdm.h90 petscviewer.h90 petscdmredundant.h90 petscdmcomplex.h90 petscmat.h90 petscmatfd.h90 petscpcgasm.h90 petscdmadda.h90 petscpcmg.h90 petscdmda.h90 petscprofiling.h90 petscvec.h90 petscpetscthreadcomm.h90 petscsys.h90 petscis.h90 petscpcexotic.h90 petscsemilagrange.h90 petscmatorderings.h90 petscsnesfas.h90 petscdmcartesian.h90 petscao.h90 petscdmmesh.h90 petscdmiga.h90 petscpf.h90 petscdmshell.h90 petscsnes.h90 petscts.h90
DIRS     =
LIBBASE   = libpetscvec
LOCDIR    = include/finclude/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
