
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  =
CFLAGS   =
FFLAGS   =
SOURCEC  = sysiof.c mprintf.c mpiuopenf.c
OBJSC    = sysiof.o mprintf.o mpiuopenf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/fileio/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
