
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  = 
CFLAGS   =
FFLAGS   =
SOURCEC  = pinitf.c ptypef.c tagmf.c gcommf.c optionsf.c inheritf.c destroyf.c
OBJSC    = pinitf.o ptypef.o tagmf.o gcommf.o optionsf.o inheritf.o destroyf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/objects/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
