
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = threadcommf.c
OBJSC    = threadcommf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	 = libpetscsys
LOCDIR   = src/sys/threadcomm/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
