
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mumpsf.c
OBJSC    = mumpsf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	 = libpetscmat
LOCDIR	 = src/mat/impls/aij/mpi/mumps/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
