
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  = 
CFLAGS   =
FFLAGS   =
SOURCEC  = fpf.c errf.c signalf.c adebugf.c
OBJSC    = fpf.o errf.o signalf.o adebugf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/error/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
