
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = tsadaptf.c
OBJSC    = tsadaptf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscts
LOCDIR   = src/ts/adapt/interface/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
