
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = snesmfjf.c
OBJSC    = snesmfjf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscsnes
LOCDIR   = src/snes/mf/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
